Feature: We can classify groups
  When running the groups task, we expect a list of groups to be classified

Scenario: Groups analysis 
    Given a file "/tmp/sequences.fasta" with fasta sequences
    When I successfully run `ecf_classify groups /tmp/sequences.fasta`
    Then the stdout should contain "ID	Group"

Scenario: Probs file
    Given a file named "tmp/sequences.fasta" with:
    """
    >ECF_78
    MANEEQRLISAAQAGDLDSFNQIVRLYETRVYNLCYRMLGDTDAAADATQDTFISAFRHLANFRGGALKSWLLRIATNTCYDVLRTRKRRPSVSLDKEPDDEGNRLDLPDPGASLDELMLQQELSAAIQRGLAELPEDQRIVIILSDIQGLAYEEIAHITGVQLGTVKSRLSRARAKLRDILRAGELLPLKFRLDDETTT
    >ECF_35310
    MADEEQRLIRSAQTGDLDAFNQLVRLYETRIYNLCYRMLGDADAAADATQDAFIAAFRNLRSFRGGTFKAWLLRIATNACYDVLRARKRRPAVSLEREHDEEERHRGELPDPGESLDDTMVRQELGAAIQRALAELPDDQRIVIILSDIQGLAYEEIARVTGVQLGTVKSRLSRARAKLRDILRAGEHLPSKFRLDDETGASR
    >ECF_37804
    MHARPDADEAELLTRSQNGDVSAFNELVLRYQSSVYNVALRMLGDADLAADITQDTFLAAFRHLANFRGGTAFRSWLLRITTNLVYDHWRRQRRHPEESLEAASDEDDPQSPVTLAQLASADLEANPELYLLHQELQELIQRGLAELPPEQRLAVILCDIEGLSYEEIAAVMQTMLGTVRSRIARGRSRLRAYLARHQELLPRPFRSP
    >ECF_43737
    MTDAERQWVSAAKAGDVEAFNQLVRMYEGRVYGLAYRMLGDSDSAADVAQDTFISAFKAIKRFREGSFAAWLLRIATNACYDVLRAQKRRRTSSMDQMLAGDDDSPGEQFEDQSLPLDQHMINRELQAAIQAGLATLPEDQRAVLIMCDIQGFAYEEIAAATDTQLGTVKSRLSRARAKLRDYLKSRELLPTAER
    >ECF_157600
    MEGRTSDDSHLVDRLRRGDARAFDELVTAYQHRVFSVALRMLRNRTEAEEVAQEVFLRVYRTVAAFRGDAKLSTWLYAIASRLCLNRLASSDRRVTREGDETLTRLASGDATPVDELERSELEATLHRAIAELPEERRIVVVLRDLEGLSYEEIAAALDLELGTVRSRLHRARMDLKEKLERFLP
    >ECF_158663
    MDRRTSDDSHLVDRLRRGDARAFDELVTAYQHRVFSVALRMLRNRTEAEEVAQEVFLRVYRTVAAFRGDAKLSTWLYAIASRLCLNRLASSDRRVTREGDETLTRLASGDATPVDELERSELEATLHRAIAELPEERRIVVVLRDLEGLSYEEIAAALDLELGTVRSRLHRARMDLKEKLERFLP
    >ECF_161198
    MRESVPDPPGLVERLRAGDPVAFEELVRTYQHRVFGVAVRMLGNAAEAEEIAQEVFLRVHRSVGEFRGEAKLSTWLYAITSRLCLNRLASAERRHPRAGADALEDVPASDTGGGLEREEVTTALRQAIAALPEERRIVVVLRDVEGLSYEEIARALDLEPGTVRSRLHRARLDLKAKLERFLP
    >ECF_161528
    MQGRPGGDPHLVDRLRRGDPRAFEELVIAYQHRVFGVALRMLRNRSEAEEIAQEVFLQVHGAVEDFRGEAKLSTWLYAITSRLCLNRLAAGERRVAREGHETLERLTADVDPAAQLERGELEAALQRAITELPEERRIVVVLRDLEGLPYDEIAEVLDLPVNTVRSRLHRARLDLKAKLERFLP
    >ECF_165573
    MQEGTAAEVLERLRAGDARAFEDLVVAYQHRVFSIAYRMLGSRAEAEEAAQEVFLRVHRGIAEFRGESKLSTWLYAITSRLCLNRLASGERRMARAREAEETLTGLPSADGDAAARMERSETEAALHRAIAELPDERRIVVVLRDLEGLSYEEIADTLGLTLGTVRSRLHRARLELRERLEKFLP
    >ECF_166121
    MEGRVGDDSDLEERLRRGDPRAFEDLVIAYQHRVFGVALRMLRNRSEAEEIAQEVFLRVHRAVEDFRGEAKLSTWLYAITSRLCLNRLASGERRMAREGEESLERLRGDADPAAHVERVELEAALQRAITELPEERRIVVVLRDFEGLSYEEIAAALDLPLGTVRSRLHRARTDLKEKLERFLP
    >NP_796434.1 RNA polymerase ECF-type sigma factor [Vibrio parahaemolyticus RIMD 2210633]
    MATTSALTHIIQQWQSGNKQAESELYQFAYLQLRKIAQQERERNAEKYGTDNMVLADSVNSTTALIHDAY
    LKMSNCDMSEIATKRDFFLMAAKVMRQILIDNARSHQAQKRQHITLMKDEEDRFEQLIIMDKALDSFSTR
    YPRQSSALKLKYLMGMKNQEISELLECSASLIEKDLKFSRSWLQSRMAHA
    """
    And a file named "tmp/prods.txt" should not exist
    When I run `ecf_classify groups tmp/sequences.fasta -p tmp/prods.txt`
    Then there should be output
    Then a file named "tmp/prods.txt" should exist

